---
- name: install server
  hosts: test 

  tasks:
  - name: install git
    yum: 
      name: git
  
  - name: install java
    yum: 
      name: java-11-openjdk-devel


  - name: install maven
    yum:
      name: maven  

  - name: pull project
    git: 
      repo: 'https://github.com/spring-projects/spring-petclinic.git'
      dest: /home/ec2-user/git
      clone: yes
      update: yes


  - name: build project
    shell: 'mvn -f /home/ec2-user/git package'

  - name: init systemctl
    copy: 
      src: ./files/petclinic.service
      dest: /etc/systemd/system


  - name: run project
    shell: 'systemctl start petclinic.service'
